#!/usr/bin/env python3
"""Generate a TOML config for a Stage E smoke run.

This script is invoked by the Stage E shell scripts to produce a
``config.toml`` that the LTX training worker can consume. It clones
``backend/training_worker/presets/character_v1.toml`` semantics but
overrides the phase ``ends_at_step`` values so each smoke run is short
enough to complete in minutes instead of hours.

Usage:
    python3 stage_e_generate_config.py \\
        --out <path> \\
        --dataset-dir <path> \\
        --model-root <path> \\
        --trigger-word <word> \\
        --gpu-index <int> \\
        --phases <phase1_end> [<phase2_end> [<phase3_end> [<phase4_end>]]]

Any phase end value of 0 means "drop this phase". The generator always
emits the dataset + sampling sections matching the character preset.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


PHASE_DEFAULTS = [
    # (key, display_name, lora_rank, learning_rate, gradient_accumulation,
    #  differential_guidance, timestep_bias)
    ("phase1_capture",     "Phase 1: Capture",          48, 1e-4, 2, 3.0, "none"),
    ("phase2_refine",      "Phase 2: Refine",           32, 1e-4, 1, 2.0, "none"),
    ("phase3_polish",      "Phase 3: Polish",           32, 1e-4, 1, 1.0, "none"),
    ("phase4_high_noise",  "Phase 4: High Noise Detail", 24, 5e-5, 1, 0.0, "high_noise"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate stage E smoke run TOML config")
    parser.add_argument("--out", required=True, type=Path, help="Path to write the TOML file")
    parser.add_argument("--dataset-dir", required=True, type=str)
    parser.add_argument("--model-root", required=True, type=str)
    parser.add_argument("--trigger-word", required=True, type=str)
    parser.add_argument("--gpu-index", type=int, default=0)
    parser.add_argument(
        "--profile",
        type=str,
        choices=("image", "video"),
        default="video",
        help="Training profile (see feature_two_profile_training.md). "
        "'image' forces a single latent frame + aspect bucketing; 'video' "
        "trains at --target-frames (must be 8k+1).",
    )
    parser.add_argument(
        "--target-frames",
        type=int,
        default=25,
        help="Frames the dataset is framed to for the video profile (must be "
        "8k+1, e.g. 25, 49, 73, 121). Ignored for the image profile, which "
        "always frames to 1.",
    )
    parser.add_argument(
        "--phases",
        type=int,
        nargs="+",
        required=True,
        help="End-step values for phases 1..N. Use 0 to skip a phase.",
    )

    parser.add_argument(
        "--save-every",
        type=int,
        default=50,
        help="save_every_n_steps applied to every emitted phase",
    )
    parser.add_argument(
        "--sample-every",
        type=int,
        default=0,
        help="sample_every_n_steps applied to every emitted phase (0 disables sampling)",
    )
    return parser.parse_args()


def toml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_toml(args: argparse.Namespace) -> str:
    lines: list[str] = []
    lines.append("# Stage E smoke run config (generated by stage_e_generate_config.py)")
    lines.append("# DO NOT EDIT BY HAND. Re-run the script to regenerate.")
    lines.append("")
    # All TrainingConfig top-level fields MUST be emitted before any
    # [section] header. TOML semantics make every key after a section
    # header belong to that table, even across blank lines, so a stray
    # ``[base]`` header would silently shadow ``model_path``,
    # ``trigger_word``, and ``gpu_index`` into a non-existent
    # ``TrainingConfig.base`` field and they would be dropped during
    # pydantic validation.
    lines.append("base_lora_alpha_equals_rank = true")
    lines.append("cache_text_embeddings = true")
    lines.append("save_optimizer_state = true")
    lines.append(f"model_path = {toml_str(args.model_root)}")
    lines.append(f"trigger_word = {toml_str(args.trigger_word)}")
    lines.append(f"gpu_index = {args.gpu_index}")
    # Two-profile training selector (see feature_two_profile_training.md).
    # Emitted top-level so it binds to TrainingConfig.profile. The image
    # profile forces target_frames=1 + aspect bucketing during config
    # validation regardless of the [dataset].target_frames below.
    lines.append(f"profile = {toml_str(args.profile)}")
    lines.append("")


    for index, end_step in enumerate(args.phases):
        if end_step <= 0:
            continue
        if index >= len(PHASE_DEFAULTS):
            raise SystemExit(f"too many phases supplied ({len(args.phases)}); preset has 4")
        key, display, rank, lr, accum, dg, bias = PHASE_DEFAULTS[index]
        lines.append(f"[phases.{key}]")
        lines.append(f"display_name = {toml_str(display)}")
        lines.append(f"ends_at_step = {end_step}")
        lines.append(f"lora_rank = {rank}")
        lines.append(f"learning_rate = {lr}")
        lines.append(f"gradient_accumulation = {accum}")
        lines.append(f"differential_guidance = {dg}")
        lines.append(f"timestep_bias = {toml_str(bias)}")
        lines.append(f"save_every_n_steps = {args.save_every}")
        lines.append(f"sample_every_n_steps = {args.sample_every}")
        lines.append("")

    lines.append("[dataset]")
    lines.append(f"dataset_dir = {toml_str(args.dataset_dir)}")
    # For the image profile this is overridden to 1 during config
    # validation; for the video profile it is the real training length.
    lines.append(f"target_frames = {args.target_frames}")
    lines.append("target_resolution = [512, 512]")
    lines.append("auto_repeats = true")
    lines.append("")


    lines.append("[sampling]")
    lines.append("resolution = [512, 512]")
    lines.append("num_frames = 49")
    lines.append("guidance_scale = 10.0")
    lines.append("default_prompts = []")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    if not args.phases:
        print("ERROR: at least one --phases value is required", file=sys.stderr)
        return 2
    toml = build_toml(args)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(toml)
    print(f"wrote config: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
